source("UI/UIHelpers/ButtonBusyIndicator.R") # Load all the code needed to show feedback on a button click
tabPanel("Search",
    #Imports <head>
    tags$head(
            includeCSS("www\\css\\SearchTab.css"),
            tags$script(src = "js\\tab1_MiningTweets.js"),
            tags$script(src = "js\\tab1_MiningTweets_R.js"),
            tags$script(src = "js\\jquery.twbsPagination.min.js")
            ),
    #Specify Layout of page
    sidebarLayout(
    #Left Side Panel
    sidebarPanel(id="searchPanel", width = 4,

        tags$h1(id="twitterAnalysisOptions","Twitter Analysis Options", class = "text-center"),
        tags$hr(),
#-------------------------------------------------------------REGION AND LANGUAGE -------------------------------------------------------------#
        fluidRow(
            column(5, selectizeInput("currentSelectedCountry", "Country :",
                                        choices = c("Worldwide", getCountriesNames()),
                                        options = list(placeholder = 'Select a region'))),
            column(2, tags$div(class = "region-button-checkbox",
                            actionButton("btnMap", "", icon = NULL, width = NULL, "data-color" = "default"),
                            hidden(checkboxInput("isMapOn", "", value = F)))
                   ),
            column(5, selectizeInput("selectedLang", "Language :", choices = NULL,
                                        options = list(placeholder = 'Select a language')))
        ),
        div(id = "animation",
            conditionalPanel(condition = "input.isMapOn",
                 leafletOutput("countryMap")
            )
        ),
        tags$br(),
#-------------------------------------------------------------No. TweetS AND Its SLIDER ---------------------------------------------------------#
        fluidRow(
            column(3,
                numericInput("noTweets", "No. Tweets :" , value = 100 , step = 100,min = 1)
            ),
            column(9,
                #additional Options has been added to tab1.js (coz this related to ion.rangeSlider.js library)  
                div(style="margin-top:-3%;",
                sliderInput("noTweetsSlider", "", post =" tweets" , min = 100, max = 1500, value = 100))
            )
        ),

        #sliderInput("searchDateRange", "DateRange : ", min = Sys.Date() - 7, max = Sys.Date(), ticks = TRUE, value = c(Sys.Date() - 7 ,  Sys.Date()),
                            #dragRange = T),
#-------------------------------------------------------------  Filter Media RadioButtons -------------------------------------------------------------#

    # fluidRow(
    #   column(12,radioButtons("filterByMedia", "Tweets Media: ",choiceNames = filterByMediaNames(),choiceValues = filterByMediaValues(), selected = "All", inline = T))
    # ),
#-------------------------------------------------------------  SEARCH TEXT BOX -------------------------------------------------------------#
    div(id="searchQueryID", #used to be targeted in css
        selectizeInput("searchQuery", "Search For : ", choices = NULL, multiple = T,
                        options = list(create = TRUE, placeholder = "Enter your search query", closeAfterSelect = T, createOnBlur = T, maxItems = 5, plugins = list("remove_button", "drag_drop")))
    ),
#------------------------------------------------------------ Submit Options For Analyze ----------------------------------------------------------#
        fluidRow(
            withBusyIndicatorUI(
                actionButton("btnAnalyze", "Analyze", icon = icon("twitter"), width = "80%", class = "btn-lg", style = "margin-left:7%;")
            ),
            #To Reset Options to Their Defaults
            actionButton("resetSearchPanel", "", icon = icon("refresh")
                            , title = "Reset Inputs Fields to their defaults", class = "btn-md")
            )
    ), #sidbar Container 
    #Panel which will hold tweets .. generated by javascript
    mainPanel(
        #div for rendering our tweets to it
        tags$div(class = "tweetsContainer", id = "tweetsContainerID"),
           
        #Pagination for our tweets (page 1 2 3 4 ) to render to it through our shinytweets.js
        HTML("<ul id=\"pagination\" class=\"pagination-md\"></ul>")
        ) #End main content Container
    ) #End SidbarLayout
) #End Tab Search
